baseURL = 'https://intangiblematter.github.io'
languageCode = 'en-us'
title = 'IntangibleMatter'
theme = 'intangibletheme23'
[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Games"
        pre = "games"
        url = "/games/"
        weight = 2
    [[menu.main]]
        name = "Posts"
        pre = "posts"
        url = "/posts/"
        weight = 3
    