baseURL = 'https://intangiblematter.github.io'
languageCode = 'en-us'
title = 'IntangibleMatter'
theme = 'intangibletheme23'
enableGitInfo = true
[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Games"
        pre = "games"
        url = "https://intangiblematter.itch.io/"
        weight = 2
    [[menu.main]]
        name = "Posts"
        pre = "posts"
        url = "/posts/"
        weight = 3



[permalinks]
    posts = '/:year/:month/:day/:title/'



[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'fruity'
        tabWidth = 4
